### ISSUE TITLE
Help me quickly 

### ISSUE THREAD

**Issue by Mostafa22111** [Mizogg/Mizogg#1]
I found wallet in this page but whet i try to copy private key the page was changed how can i get back the private from caches or cookies or ip is there is way to back it or lose it dor ever 

https://mizogg.co.uk/VisualBTCv2/#javascript:void(0);#

**Comment by Mizogg** [comment]
This is just a HTML Webpage it does not record any information if it is not there then it has been lost.

Thanks Mizogg
